Class {
	#name : #M1P2C2ReferencerOutSideRefereeInSide,
	#superclass : #Object,
	#category : #'Moose-TestResources-KGB-P2InteractedReferencerReferee'
}

{ #category : #'Moose-Cook-ModelFamix2-Test-Methods' }
M1P2C2ReferencerOutSideRefereeInSide >> m1p2c2Mtd1 [ 
	 
	^M3P7C14ReferencerOutSideRefereeOutSide m3p7c14InstCreation m3p7c14Mtd4
]

{ #category : #'Moose-Cook-ModelFamix2-Test-Methods' }
M1P2C2ReferencerOutSideRefereeInSide >> m1p2c2Mtd2 [ 
	 
	^M3P7C14ReferencerOutSideRefereeOutSide new m3p7c14Mtd2.
]
