Class {
	#name : #FamixTest1Model,
	#superclass : #MooseModel,
	#category : #'Famix-Test1-Entities-Model'
}

{ #category : #accessing }
FamixTest1Model class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixTest1Model class >> annotation [
	<FMClass: #FamixTest1Model super: #MooseModel>
	<package: #'Famix-Test1-Entities'>
	<generated>
]
