"
FAMIXSmalltalkMonticelloSourceLanguage represents the fact that the language is Smalltalk (extracted from Monticello).
"
Class {
	#name : #FAMIXSmalltalkMonticelloSourceLanguage,
	#superclass : #FAMIXSourceLanguage,
	#category : #'Moose-MonticelloImporter'
}

{ #category : #meta }
FAMIXSmalltalkMonticelloSourceLanguage class >> annotation [
	<MSEClass: #SmalltalkMonticelloSourceLanguage super: #FAMIXSourceLanguage>
	<package: #FAMIX>
]
