Extension { #name : #UndefinedObject }

{ #category : #'*Moose-Query' }
UndefinedObject >> allAtAnyScope: aCollectionOfFamixClasses in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allAtAnyScope: aCollectionOfFamixClasses in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allAtScope: aFAMIXScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allAtScope: aFAMIXScope in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allToAnyScope: aCollectionOfFamixClasses in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allToAnyScope: aCollectionOfFamixClasses in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allToScope: aFAMIXScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allToScope: aFAMIXScope in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allWithScope: aFAMIXScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> allWithScope: aFAMIXScope in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> atAnyScope: aCollectionOfFamixScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> atAnyScope: aCollectionOfFamixScope in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> atScope: aFAMIXScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> atScope: aFAMIXScope in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> toAnyScope: aCollectionOfFamixClasses in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> toAnyScope: aCollectionOfFamixClasses in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> toScope: aFAMIXScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> toScope: aFAMIXScope in: aCollection until: aRejectBlock [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> withScope: aFAMIXScope in: aCollection [
	^ aCollection
]

{ #category : #'*Moose-Query' }
UndefinedObject >> withScope: aFAMIXScope in: aCollection until: aRejectBlock [
	^ aCollection
]
