Class {
	#name : #FmxCTypeGenerated,
	#superclass : #FmxCEntityGenerated,
	#category : #'FmxC-Entities'
}

{ #category : #meta }
FmxCTypeGenerated class >> annotation [

	<MSEClass: #Type super: #FmxCEntityGenerated>
	<package: #FmxC>
	^self
]

{ #category : #meta }
FmxCTypeGenerated class >> requirements [

	^ {  }
]

{ #category : #meta }
FmxCTypeGenerated class >> statefulTraits [

	<statefulTraits>
	^ {}
]
