Trait {
	#name : #FamixStTLCOMMetrics,
	#category : #'Famix-PharoSmalltalk-Entities-Traits'
}

{ #category : #meta }
FamixStTLCOMMetrics classSide >> annotation [

	<MSEClass: #TLCOMMetrics super: #Trait>
	<generated>
	<package: #'Famix-PharoSmalltalk-Entities'>
	^self
]

{ #category : #generator }
FamixStTLCOMMetrics classSide >> generatedSlotNames [
	<generated>
	'FamixStTLCOMMetrics class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FamixStTLCOMMetrics classSide >> generatedTraitNames [
	<generated>
	^ #()
]
