"
An abstract class for function prototype parser handlers.
"
Class {
	#name : #XPathFunctionPrototypeParserHandler,
	#superclass : #XPathParserHandler,
	#category : #'XPath-Core-Parsers'
}

{ #category : #handling }
XPathFunctionPrototypeParserHandler >> handleArgument: anArgument [
]

{ #category : #handling }
XPathFunctionPrototypeParserHandler >> handleFunctionName: aName [
]

{ #category : #handling }
XPathFunctionPrototypeParserHandler >> handleOptionalArgument: anArgument [
]

{ #category : #handling }
XPathFunctionPrototypeParserHandler >> handleReturnType: aReturnType [
]

{ #category : #handling }
XPathFunctionPrototypeParserHandler >> handleUnboundedArgument: anArgument [
]
