"
This baseline claims the menu-bar and confs. It should be unified with the finder maybe?


	spec
		package: 'Moose-MenuBar';
		package: 'Moose-Configuration'
"
Class {
	#name : #BaselineOfMooseIDE,
	#superclass : #BaselineOf,
	#category : #BaselineOfMooseIDE
}

{ #category : #baselines }
BaselineOfMooseIDE >> baseline: spec [
	<baseline>
	spec
		package: 'Moose-MenuBar';
		package: 'Moose-Configuration'
]
