Class {
	#name : #FamixCSharpAbstractFileAnchor,
	#superclass : #FamixCSharpSourceAnchor,
	#traits : 'FamixTFileAnchor',
	#classTraits : 'FamixTFileAnchor classTrait',
	#category : #'Famix-CSharp-Entities-Entities'
}

{ #category : #meta }
FamixCSharpAbstractFileAnchor class >> annotation [

	<MSEClass: #AbstractFileAnchor super: #FamixCSharpSourceAnchor>
	<package: #'Famix-CSharp-Entities'>
	<generated>
	^self
]
