name: Get versions file contents

# Read the content of the file versions.json. 
# Output is a json string.

on:
  workflow_call:
    inputs: 
      file-path:
        required: true
        type: string
    outputs:
      versions:
        description: "Versions informations as a Json string"
        value: ${{ jobs.get-versions.outputs.versions }}

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs: 
      versions: ${{ steps.read-file.outputs.versions }}
    steps:
      - name: Get pharo versions
        run: |
          echo "versions=$VERSIONS" >> $GITHUB_OUTPUT
        env:
          VERSIONS: fromJSON(${{ vars.PHARO_VERSIONS }}).development
