name: Stable

on:
  release:
    types: [created, edited]
  workflow_dispatch: 

jobs:
  run-tests-and-update-release:
    name: Run tests and update release
    uses: moosetechnology/.github/.github/workflows/test-and-release.yml@main
    with:
       pre-upload-script: "MooseVersion current commitHash: '$GITHUB_SHA'. (Smalltalk tools toolNamed: #mooseWelcome) closePharoWelcomeThenOpen"
