name: Development
run-name: >-
  ${{ vars.BRANCHES_CONFIGURATION
  && fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name] 
  && fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name].run-name 
  || github.ref_name }} #Dedicated name in the Repository variable OR branch name

on:
  push:
    branches:
      - development
      - v10
      - v11
  schedule:
    - cron:  '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests-and-update-release:
    name: Run tests and update release
    uses: moosetechnology/.github/.github/workflows/test-and-release.yml@main
    with:
      pre-upload-script: "MooseVersion current commitHash: '$GITHUB_SHA'. (Smalltalk tools toolNamed: #mooseWelcome) closePharoWelcomeThenOpen"
