name: Pull-request

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  run:
    uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
    secrets: inherit
    with:
        create-artifact: true
