Class {
	#name : #FamixTest3UnknownSourceLanguage,
	#superclass : #FamixTest3SourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Test3-Entities-Entities'
}

{ #category : #meta }
FamixTest3UnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixTest3SourceLanguage>
	<package: #'Famix-Test3-Entities'>
	<generated>
	^self
]
